<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>بحث: {{ $query ?? '' }} | دليل سوريا التجاري</title>
    <meta name="description" content="نتائج البحث عن {{ $query ?? '' }} في دليل سوريا التجاري">
    <meta name="robots" content="noindex, follow">
    
    <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
    <style>.business-card{transition:all .3s ease;}.business-card:hover{transform:translateY(-5px);box-shadow:0 20px 25px -12px rgba(0,0,0,.2);}.filter-active{background-color:#10b981!important;color:white!important;}</style>
</head>
<body class="bg-slate-50 font-sans antialiased">

    <header class="bg-gradient-to-r from-slate-900 to-slate-800 text-white py-4 px-6 shadow-lg sticky top-0 z-50"><div class="max-w-7xl mx-auto flex flex-wrap justify-between items-center gap-4"><a href="{{ route('home') }}" class="flex items-center gap-2"><div class="w-8 h-8 bg-emerald-600 rounded-lg flex items-center justify-center"><i class="fas fa-chart-line text-white text-sm"></i></div><span class="font-black">دليل سوريا التجاري</span></a><form action="{{ route('search') }}" method="GET" class="flex-1 max-w-md"><div class="relative"><i class="fas fa-search absolute right-4 top-1/2 transform -translate-y-1/2 text-slate-400"></i><input type="text" name="search" value="{{ $query ?? '' }}" placeholder="ابحث عن منشأة، خدمة، أو منتج..." class="w-full bg-white/10 border border-white/20 rounded-xl py-2 pr-10 pl-4 text-white placeholder-slate-400 focus:outline-none focus:border-emerald-500"><button type="submit" class="absolute left-2 top-1/2 transform -translate-y-1/2 bg-emerald-600 hover:bg-emerald-700 text-white px-3 py-1 rounded-lg text-xs">بحث</button></div></form><a href="{{ route('business.create') }}" class="text-sm bg-emerald-600 hover:bg-emerald-700 px-4 py-2 rounded-xl"><i class="fas fa-plus-circle ml-1"></i> أضف منشأتك</a></div></header>

    <div class="max-w-7xl mx-auto px-4 py-8"><div class="flex flex-col lg:flex-row gap-8">
        
        <aside class="lg:w-72 space-y-6"><div class="bg-white rounded-2xl shadow-sm p-5 sticky top-24"><h3 class="font-bold text-slate-900 mb-4 flex items-center gap-2"><i class="fas fa-sliders-h text-emerald-600"></i> فلترة النتائج</h3>
        <form action="{{ route('search') }}" method="GET" id="filterForm"><input type="hidden" name="search" value="{{ $query ?? '' }}">
            <div class="mb-5"><label class="block text-xs font-bold text-slate-700 mb-2">📍 المحافظة</label><select name="location" class="w-full bg-slate-50 border border-slate-200 rounded-xl p-2.5 text-sm"><option value="">جميع المحافظات</option>@foreach($governorates ?? [] as $gov)<option value="{{ $gov->slug }}" {{ request('location') == $gov->slug ? 'selected' : '' }}>{{ $gov->name }}</option>@endforeach</select></div>
            <div class="mb-5"><label class="block text-xs font-bold text-slate-700 mb-2">📁 التصنيف</label><select name="category" class="w-full bg-slate-50 border border-slate-200 rounded-xl p-2.5 text-sm"><option value="">جميع التصنيفات</option>@foreach($categories as $cat)<option value="{{ $cat->slug }}" {{ request('category') == $cat->slug ? 'selected' : '' }}>{{ $cat->icon ?? '📁' }} {{ $cat->name }}</option>@endforeach</select></div>
            <div class="mb-5"><label class="block text-xs font-bold text-slate-700 mb-2">📊 ترتيب حسب</label><select name="sort" class="w-full bg-slate-50 border border-slate-200 rounded-xl p-2.5 text-sm"><option value="latest" {{ request('sort') == 'latest' ? 'selected' : '' }}>الأحدث</option><option value="rating" {{ request('sort') == 'rating' ? 'selected' : '' }}>الأعلى تقييماً</option><option value="oldest" {{ request('sort') == 'oldest' ? 'selected' : '' }}>الأقدم</option></select></div>
            <div class="mb-5"><label class="flex items-center gap-2 cursor-pointer"><input type="checkbox" name="delivery" value="1" {{ request('delivery') ? 'checked' : '' }} class="w-4 h-4 text-emerald-600 rounded"><span class="text-sm text-slate-700">🛵 يتوفر توصيل فقط</span></label></div>
            <button type="submit" class="w-full bg-emerald-600 hover:bg-emerald-700 text-white font-bold py-2.5 rounded-xl"><i class="fas fa-filter ml-1"></i> تطبيق الفلترة</button>
            @if(request()->anyFilled(['location','category','sort','delivery']))<a href="{{ route('search', ['search' => $query]) }}" class="block text-center text-xs text-slate-500 mt-3 hover:text-emerald-600"><i class="fas fa-undo-alt ml-1"></i> إعادة ضبط</a>@endif
        </form></div></aside>
        
        <main class="flex-1"><div class="bg-white rounded-2xl shadow-sm p-5 mb-6"><div class="flex flex-wrap justify-between items-center gap-3"><div><h1 class="text-xl font-black text-slate-900 flex items-center gap-2"><i class="fas fa-search text-emerald-600"></i> نتائج البحث</h1><p class="text-sm text-slate-500 mt-1"><span class="font-bold text-emerald-600">{{ $businesses->total() }}</span> نتيجة لـ "<span class="font-bold">{{ $query ?? '' }}</span>" @if(request('location')) في <span class="font-bold">{{ \App\Models\Location::where('slug', request('location'))->first()->name ?? '' }}</span>@endif</p></div><div class="text-xs text-slate-400"><i class="far fa-clock ml-1"></i> وقت البحث: {{ round(microtime(true) - LARAVEL_START, 2) }} ثانية</div></div></div>
        
        @if($businesses->count() > 0)
        <div class="grid grid-cols-1 md:grid-cols-2 gap-6">@foreach($businesses as $bus)<div class="business-card bg-white rounded-2xl overflow-hidden shadow-sm hover:shadow-xl transition-all"><div class="relative h-40 overflow-hidden bg-slate-200"><img src="{{ $bus->cover_url }}" alt="{{ $bus->title }}" class="w-full h-full object-cover" loading="lazy"><div class="absolute top-3 right-3 flex gap-1">@if($bus->delivery_available)<span class="bg-emerald-500 text-white text-[10px] font-bold px-2 py-0.5 rounded">🛵 توصيل</span>@endif@if($bus->verification_type=='official')<span class="bg-amber-500 text-white text-[10px] font-bold px-2 py-0.5 rounded">👑 رسمي</span>@elseif($bus->verification_type=='verified')<span class="bg-blue-500 text-white text-[10px] font-bold px-2 py-0.5 rounded">✓ موثق</span>@endif</div></div><div class="p-4"><div class="flex items-start justify-between gap-2"><h3 class="font-bold text-slate-900 hover:text-emerald-600"><a href="{{ route('business.show', $bus->slug) }}">{{ $bus->title }}</a></h3><img src="{{ $bus->logo_url }}" class="w-8 h-8 rounded-lg object-cover"></div><p class="text-xs text-slate-500 mt-2 line-clamp-2">{{ $bus->excerpt }}</p><div class="flex flex-wrap gap-3 mt-3 pt-3 border-t border-slate-100 text-xs text-slate-500"><span><i class="fas fa-folder"></i> {{ $bus->category->name ?? 'عام' }}</span><span><i class="fas fa-map-marker-alt"></i> {{ $bus->location->parent->name ?? '' }} - {{ $bus->location->name ?? '' }}</span>@if($bus->rating_avg>0)<span class="text-amber-500"><i class="fas fa-star"></i> {{ number_format($bus->rating_avg,1) }}</span>@endif</div><div class="mt-3 flex gap-2"><a href="tel:{{ $bus->phone }}" class="flex-1 bg-slate-100 hover:bg-emerald-600 text-slate-700 hover:text-white text-center text-xs font-bold py-2 rounded-xl"><i class="fas fa-phone ml-1"></i> اتصل</a><a href="{{ route('business.show', $bus->slug) }}" class="flex-1 bg-emerald-50 hover:bg-emerald-600 text-emerald-600 hover:text-white text-center text-xs font-bold py-2 rounded-xl">تفاصيل <i class="fas fa-arrow-left mr-1"></i></a></div></div></div>@endforeach</div>
        <div class="mt-8">{{ $businesses->appends(request()->query())->links() }}</div>
        @else
        <div class="bg-white rounded-2xl shadow-sm p-12 text-center"><i class="fas fa-search text-6xl text-slate-300 mb-4 block"></i><h3 class="text-xl font-bold text-slate-700 mb-2">لا توجد نتائج</h3><p class="text-slate-500 mb-6">لم نعثر على منشآت تطابق "<span class="font-bold">{{ $query ?? '' }}</span>"</p><div class="flex flex-wrap gap-3 justify-center"><a href="{{ route('home') }}" class="bg-slate-100 hover:bg-slate-200 text-slate-700 font-bold px-5 py-2 rounded-xl"><i class="fas fa-home"></i> العودة للرئيسية</a><a href="{{ route('business.create') }}" class="bg-emerald-600 hover:bg-emerald-700 text-white font-bold px-5 py-2 rounded-xl"><i class="fas fa-plus-circle"></i> أضف منشأتك الآن</a></div></div>
        @endif
        </main>
    </div></div>

    <script>document.querySelectorAll('#filterForm select, #filterForm input[type="checkbox"]').forEach(el=>{el.addEventListener('change',()=>{document.getElementById('filterForm').submit();});});</script>
</body>
</html>